### ISSUE TITLE
rpi architecture issue? 

### ISSUE THREAD

**Issue by jbarneson** [mguinness/IntelliCenterGateway#3]
attempted deploying on a spare pi3 i had laying around and had trouble with the docker run command. Returned this error: 

`standard_init_linux.go:207: exec user process caused "exec format error"`

Seems like from some googling that might be architecture related. Have you successfully deployed this to a pi? or is there maybe some changes needed?

To test my suspicion, i deployed to my x86 server and everything installed and started up perfectly.

**Comment by mguinness** [comment]
To be honest I'm not too familiar w/ docker and the config was provided in a PR.  @Gibby do you have any suggestions?

**Comment by Gibby** [comment]
@jbarneson you would need to do docker build on the pi to build an image for ARM

**Comment by mguinness** [comment]
Also give [Deploying ASP.NET Core Docker image from x86 to ARM (Raspberry Pi) in VS2019](https://stackoverflow.com/questions/60158729) a try.

**Comment by mguinness** [comment]
@jbarneson I updated the docker file to support RPI.  Please test and close issue if it works.

@Gibby Let me know if this is a problem for you.  We can add additional docker files for other architectures.

**Comment by rmonty** [comment]
Mine worked great on a RPI 2.  Up and running and even added the docker --restart to enable it to startup if the PI reboots.

**Comment by Gibby** [comment]
@mguinness yeah it breaks the none PI docker images. Best practices is a separate Dockerfile for each type.

Then in Docker Hub setup your auto build rules to build and tag the different architectures supported.

**Comment by Gibby** [comment]
Saw how you were doing it with actions, I created a PR to support both. https://github.com/mguinness/IntelliCenterGateway/pull/6

**Comment by mguinness** [comment]
Docker image for linux/arm now available on [Docker Hub](https://hub.docker.com/r/mguinness/intellicentergateway).
